app:
  name: "作业智能批阅系统"
  version: "1.0.0"
dify:
  api:
    apiKey: "app-h2yIzEsq6W2C5eHN0MtDVRt2"   # Dify应用的API密钥
    baseUrl: "http://localhost:5001/v1" # Dify API服务的地址
python:
  exe: "E:\\python.exe"
  script:
    mdToDocxPath: "src/main/java/com/javascene/gradingfx/pyscript/md_to_docx.py"
    docxToMdPath: "src/main/java/com/javascene/gradingfx/pyscript/docx_to_md.py"
file:
  zipPath: "src/main/java/com/javascene/gradingfx/file/zip"
  unzipPath: "src/main/java/com/javascene/gradingfx/file/unzip"
  tempPath: "src/main/java/com/javascene/gradingfx/file/temp"
  wordPath: "src/main/java/com/javascene/gradingfx/file/word"
  excelPath: "src/main/java/com/javascene/gradingfx/file/excel"
  resultPath: "src/main/java/com/javascene/gradingfx/file/result"
data:
  task: "src/main/java/com/javascene/gradingfx/data/task"
  totalTask: "src/main/java/com/javascene/gradingfx/data/totalTask.json"
  result: "src/main/java/com/javascene/gradingfx/data/results.json"
  standard: "src/main/java/com/javascene/gradingfx/data/standard"
  currentStandard: "src/main/java/com/javascene/gradingfx/data/currentStandard.json"
  exportConfig: "src/main/java/com/javascene/gradingfx/data/exportConfig.json"
